spring:
  datasource:
    url: jdbc:h2:mem:bankapiprototype_db
    username: pedro
    password: 1234
  jpa:
    hibernate:
      properties:
        hibernate.format_sql: true
    show-sql: true
    naming:
      physical-strategy=org:
        hibernate:
          boot:
            model:
              naming: PhysicalNamingStrategyStandardImpl

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs